package com.reskyu.consumer.data.model

import com.google.firebase.Timestamp

/**
 * Listing
 *
 * Represents a food-drop document in the Firestore `/listings/{listingId}` collection.
 * This is the core entity consumers browse on the Home screen.
 *
 * Firestore path: /listings/{listingId}
 * Fields:
 *  - id              : Document ID (auto-generated by Firestore)
 *  - merchantId      : UID of the merchant who created this listing
 *  - businessName    : Denormalized from merchant for fast UI rendering
 *  - heroItem        : Short description of the food (e.g., "Assorted Pastries box")
 *  - dietaryTag      : VEG | NON_VEG | VEGAN | JAIN
 *  - mealsLeft       : Atomic counter — decremented via Firestore transactions on claim
 *  - originalPrice   : Original price in INR before discount
 *  - discountedPrice : Price consumer pays in INR
 *  - imageUrl        : Cloudinary-hosted image URL
 *  - geoHash         : GeoHash string copied from merchant for proximity queries
 *  - expiresAt       : Firestore Timestamp when this listing expires
 *  - status          : OPEN | SOLD_OUT | CANCELLED
 */
data class Listing(
    val id: String = "",
    val merchantId: String = "",
    val businessName: String = "",
    val heroItem: String = "",
    val dietaryTag: String = DietaryTag.VEG.name,
    val mealsLeft: Int = 0,
    val originalPrice: Double = 0.0,
    val discountedPrice: Double = 0.0,
    val imageUrl: String = "",
    val geoHash: String = "",
    val expiresAt: Timestamp = Timestamp.now(),
    val status: String = ListingStatus.OPEN.name
) {
    /** No-arg constructor required by Firestore deserialization */
    constructor() : this("", "", "", "", DietaryTag.VEG.name, 0, 0.0, 0.0, "", "", Timestamp.now(), ListingStatus.OPEN.name)
}
