package com.reskyu.consumer.data.model

import com.google.firebase.Timestamp

/**
 * Listing
 *
 * Represents a food-drop document in the Firestore `/listings/{listingId}` collection.
 * This is the core entity consumers browse on the Home screen.
 *
 * Firestore path: /listings/{listingId}
 * Fields (shared):
 *  - id              : Document ID (auto-generated by Firestore)
 *  - merchantId      : UID of the merchant who created this listing
 *  - businessName    : Denormalized from merchant for fast UI rendering
 *  - heroItem        : Food description for STANDARD; hint item for MYSTERY_BOX
 *  - dietaryTag      : VEG | NON_VEG | VEGAN | JAIN
 *  - mealsLeft       : Atomic counter — decremented via Firestore transactions on claim
 *  - originalPrice   : Original price in INR (0 for mystery boxes)
 *  - discountedPrice : Price consumer pays in INR
 *  - imageUrl        : Cloudinary-hosted image URL
 *  - geoHash         : GeoHash string copied from merchant for proximity queries
 *  - expiresAt       : Firestore Timestamp when this listing expires
 *  - status          : OPEN | SOLD_OUT | CANCELLED
 *
 * Mystery Box-only fields (listingType == "MYSTERY_BOX"):
 *  - listingType     : "MYSTERY_BOX" (defaults to "STANDARD" for old documents)
 *  - boxType         : Category label e.g. "BAKERY", "SWEETS", "MEALS"
 *  - priceRangeMin   : Lower bound of contents' retail value (INR)
 *  - priceRangeMax   : Upper bound of contents' retail value (INR)
 *  - itemCount       : Number of items in the box
 */
data class Listing(
    val id: String = "",
    val merchantId: String = "",
    val businessName: String = "",
    val heroItem: String = "",
    val dietaryTag: String = DietaryTag.VEG.name,
    val mealsLeft: Int = 0,
    val originalPrice: Double = 0.0,
    val discountedPrice: Double = 0.0,
    val imageUrl: String = "",
    val geoHash: String = "",
    val lat: Double = 0.0,
    val lng: Double = 0.0,
    val expiresAt: Timestamp = Timestamp.now(),
    val status: String = ListingStatus.OPEN.name,

    // ── Mystery Box fields ─────────────────────────────────────────────────────
    /** "STANDARD" or "MYSTERY_BOX". Defaults to STANDARD for backward compatibility. */
    val listingType: String = "STANDARD",
    /** Category of the mystery box: "BAKERY", "SWEETS", "MEALS", etc. */
    val boxType: String = "",
    /** Lower bound of the box contents' retail value (INR) */
    val priceRangeMin: Double = 0.0,
    /** Upper bound of the box contents' retail value (INR) */
    val priceRangeMax: Double = 0.0,
    /** Number of items included in the box */
    val itemCount: Int = 0
) {
    /** True when this is a mystery box — drives UI branching in cards and detail screen. */
    val isMysteryBox: Boolean get() = listingType == "MYSTERY_BOX"

    /** No-arg constructor required by Firestore deserialization */
    constructor() : this(
        "", "", "", "", DietaryTag.VEG.name, 0, 0.0, 0.0, "", "", 0.0, 0.0,
        Timestamp.now(), ListingStatus.OPEN.name,
        "STANDARD", "", 0.0, 0.0, 0
    )
}
